# Generated by Django 3.1 on 2020-08-11 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filedata9', '0002_order_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.CharField(choices=[('Out for Delivery', 'Out for Delivery'), ('Delivered', 'Delivered'), ('Pending', 'Pending')], max_length=200, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='order',
        ),
    ]
